# Site Settings
title:            Jonathan (Jonny) Johannes 
email:            jonny@jonnyjohannes.com
url:              https://jonnyjohannes.github.io
meta_author:      Johannes Jonathan

sass:
  sass_dir: assets/stylesheets

